export const reducerCases = {
  SET_TOKEN: 'SET_TOKEN',
  SET_DEVICE: 'SET_DEVICE',
  SET_USER: 'SET_USER',
  SET_SEARCH_RESULTS: 'SET_SEARCH_RESULTS',
  SET_PLAYING: 'SET_PLAYING',
  SET_PLAYER_STATE: 'SET_PLAYER_STATE'
}
